// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateBranchData, CreateBranchErrors, CreateBranchResponses, CreateProjectData, CreateProjectErrors, CreateProjectResponses, CreateSnapshotData, CreateSnapshotErrors, CreateSnapshotResponses, DeleteBranchData, DeleteBranchErrors, DeleteBranchResponses, DeleteObjectData, DeleteObjectErrors, DeleteObjectResponses, DeleteProjectData, DeleteProjectErrors, DeleteProjectResponses, DeleteSnapshotData, DeleteSnapshotErrors, DeleteSnapshotResponses, ForkBranchAtLsnData, ForkBranchAtLsnErrors, ForkBranchAtLsnResponses, GetBranchData, GetBranchErrors, GetBranchResponses, GetObjectData, GetObjectErrors, GetObjectResponses, GetProjectData, GetProjectErrors, GetProjectResponses, GetSnapshotData, GetSnapshotErrors, GetSnapshotResponses, ListBranchesData, ListBranchesErrors, ListBranchesResponses, ListObjectsData, ListObjectsErrors, ListObjectsResponses, ListProjectsData, ListProjectsResponses, ListSnapshotsData, ListSnapshotsErrors, ListSnapshotsResponses, MergeBranchData, MergeBranchErrors, MergeBranchResponses, PutObjectData, PutObjectErrors, PutObjectResponses, ResetBranchFromParentData, ResetBranchFromParentErrors, ResetBranchFromParentResponses, RestoreBranchData, RestoreBranchErrors, RestoreBranchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List projects with cursor-based pagination.
 */
export const listProjects = <ThrowOnError extends boolean = false>(options?: Options<ListProjectsData, ThrowOnError>) => (options?.client ?? client).get<ListProjectsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects',
    ...options
});

/**
 * Create a new project.
 */
export const createProject = <ThrowOnError extends boolean = false>(options?: Options<CreateProjectData, ThrowOnError>) => (options?.client ?? client).post<CreateProjectResponses, CreateProjectErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects',
    ...options
});

/**
 * Delete a project (soft-delete).
 */
export const deleteProject = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectData, ThrowOnError>) => (options.client ?? client).delete<DeleteProjectResponses, DeleteProjectErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}',
    ...options
});

/**
 * Get a project by ID.
 */
export const getProject = <ThrowOnError extends boolean = false>(options: Options<GetProjectData, ThrowOnError>) => (options.client ?? client).get<GetProjectResponses, GetProjectErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}',
    ...options
});

/**
 * List branches with cursor-based pagination.
 */
export const listBranches = <ThrowOnError extends boolean = false>(options: Options<ListBranchesData, ThrowOnError>) => (options.client ?? client).get<ListBranchesResponses, ListBranchesErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches',
    ...options
});

/**
 * Fork a new branch from an existing branch.
 *
 * The new branch inherits all objects visible on the source branch at the
 * current LSN. Writes to the new branch are independent of the source.
 */
export const createBranch = <ThrowOnError extends boolean = false>(options: Options<CreateBranchData, ThrowOnError>) => (options.client ?? client).post<CreateBranchResponses, CreateBranchErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a branch.
 *
 * The default branch cannot be deleted. A branch with child branches cannot
 * be deleted until all children are removed.
 */
export const deleteBranch = <ThrowOnError extends boolean = false>(options: Options<DeleteBranchData, ThrowOnError>) => (options.client ?? client).delete<DeleteBranchResponses, DeleteBranchErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}',
    ...options
});

/**
 * Get a branch by ID.
 */
export const getBranch = <ThrowOnError extends boolean = false>(options: Options<GetBranchData, ThrowOnError>) => (options.client ?? client).get<GetBranchResponses, GetBranchErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}',
    ...options
});

/**
 * Fork a new child branch from an existing branch at a specific LSN.
 *
 * The source branch is left completely untouched. The new branch sees only
 * history up to `lsn` — writes to it advance from there.
 * Provide exactly one of `lsn` or `snapshot_id`.
 */
export const forkBranchAtLsn = <ThrowOnError extends boolean = false>(options: Options<ForkBranchAtLsnData, ThrowOnError>) => (options.client ?? client).post<ForkBranchAtLsnResponses, ForkBranchAtLsnErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}/fork',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Merge a source branch into its direct parent.
 *
 * Replays all object writes that `source_branch_id` made since it was forked
 * onto `target_branch_id`. The source branch must be a **direct child** of the
 * target and must have **no children** of its own. After a successful merge,
 * the source branch is unchanged and may be deleted by the caller.
 *
 * All copies are applied atomically (all-or-nothing). Tombstones are
 * propagated, so deletes on the source branch will take effect on the target.
 */
export const mergeBranch = <ThrowOnError extends boolean = false>(options: Options<MergeBranchData, ThrowOnError>) => (options.client ?? client).post<MergeBranchResponses, MergeBranchErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}/merge',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List objects on a branch.
 *
 * Supports S3-style prefix/delimiter filtering for virtual directory trees.
 * Objects are resolved through the branch ancestry chain — objects from
 * parent branches are visible unless overwritten or deleted on this branch.
 */
export const listObjects = <ThrowOnError extends boolean = false>(options: Options<ListObjectsData, ThrowOnError>) => (options.client ?? client).get<ListObjectsResponses, ListObjectsErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}/objects',
    ...options
});

/**
 * Delete an object from a branch.
 *
 * Writes a tombstone at the current LSN, making the object invisible on
 * this branch without affecting ancestor branches.
 */
export const deleteObject = <ThrowOnError extends boolean = false>(options: Options<DeleteObjectData, ThrowOnError>) => (options.client ?? client).delete<DeleteObjectResponses, DeleteObjectErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}/objects/{path}',
    ...options
});

/**
 * Download an object from a branch.
 *
 * Returns the raw object bytes with `Content-Type` and `Content-Length` headers.
 * Use `HEAD` on the same path to retrieve these headers without the body.
 */
export const getObject = <ThrowOnError extends boolean = false>(options: Options<GetObjectData, ThrowOnError>) => (options.client ?? client).get<GetObjectResponses, GetObjectErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}/objects/{path}',
    ...options
});

/**
 * Write an object to a branch.
 *
 * Creates or overwrites the object at the given path. The request body is
 * the raw object content. Set `Content-Type` to the object's MIME type.
 *
 * Returns `201 Created` for a new object and `200 OK` for an overwrite.
 */
export const putObject = <ThrowOnError extends boolean = false>(options: Options<PutObjectData, ThrowOnError>) => (options.client ?? client).put<PutObjectResponses, PutObjectErrors, ThrowOnError>({
    bodySerializer: null,
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}/objects/{path}',
    ...options,
    headers: {
        'Content-Type': 'application/octet-stream',
        ...options.headers
    }
});

/**
 * Reset a branch to its parent's current state.
 *
 * Creates a new internal node forked from the branch's parent at the current
 * project LSN, then atomically updates the branch's handle to point at it.
 * The same `branch_id` is preserved. Old writes on the branch are discarded
 * (their node is orphaned). Returns 422 if the branch has no parent.
 */
export const resetBranchFromParent = <ThrowOnError extends boolean = false>(options: Options<ResetBranchFromParentData, ThrowOnError>) => (options.client ?? client).post<ResetBranchFromParentResponses, ResetBranchFromParentErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}/reset',
    ...options
});

/**
 * Rewind a branch in-place to a previous LSN, preserving its current state in a backup branch.
 *
 * The same `branch_id` is kept; its internal node is atomically swapped to a new node
 * capped at `lsn`. A backup branch is automatically created as a child of `branch_id`
 * pointing at the pre-restore node, so no history is lost.
 *
 * The backup branch prevents `branch_id` from being deleted until the backup is
 * explicitly removed. Provide exactly one of `lsn` or `snapshot_id`.
 */
export const restoreBranch = <ThrowOnError extends boolean = false>(options: Options<RestoreBranchData, ThrowOnError>) => (options.client ?? client).post<RestoreBranchResponses, RestoreBranchErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}/restore',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List snapshots for a branch with cursor-based pagination.
 */
export const listSnapshots = <ThrowOnError extends boolean = false>(options: Options<ListSnapshotsData, ThrowOnError>) => (options.client ?? client).get<ListSnapshotsResponses, ListSnapshotsErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}/snapshots',
    ...options
});

/**
 * Create a snapshot of the current branch state.
 *
 * Captures the current project LSN as the snapshot point. The snapshot can
 * be used to restore the branch to this exact state later.
 */
export const createSnapshot = <ThrowOnError extends boolean = false>(options: Options<CreateSnapshotData, ThrowOnError>) => (options.client ?? client).post<CreateSnapshotResponses, CreateSnapshotErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}/snapshots',
    ...options
});

/**
 * Delete a snapshot.
 */
export const deleteSnapshot = <ThrowOnError extends boolean = false>(options: Options<DeleteSnapshotData, ThrowOnError>) => (options.client ?? client).delete<DeleteSnapshotResponses, DeleteSnapshotErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}/snapshots/{snapshot_name}',
    ...options
});

/**
 * Get a snapshot by name.
 */
export const getSnapshot = <ThrowOnError extends boolean = false>(options: Options<GetSnapshotData, ThrowOnError>) => (options.client ?? client).get<GetSnapshotResponses, GetSnapshotErrors, ThrowOnError>({
    security: [{ scheme: 'basic', type: 'http' }],
    url: '/projects/{project_id}/branches/{branch_id}/snapshots/{snapshot_name}',
    ...options
});
