// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type BranchInfo = {
    branch_id: string;
    created_at: number;
    fork_lsn?: number | null;
    head_lsn: number;
    parent_id?: string | null;
};

export type BranchResponse = {
    branch: BranchInfo;
};

export type CreateBranchRequest = {
    source_branch_id: string;
};

export type ErrorBody = {
    /**
     * Machine-readable error code, e.g. `PROJECT_NOT_FOUND`
     */
    code: string;
    /**
     * Human-readable description of the error
     */
    message: string;
};

export type ErrorEnvelope = {
    error: ErrorBody;
};

/**
 * Exactly one of `lsn` or `snapshot_id` must be provided.
 * TODO could probably be an Enum?
 */
export type ForkRequest = {
    /**
     * LSN to fork at. Must be ≤ the source branch's current head LSN.
     */
    lsn?: number | null;
    /**
     * Snapshot ID to fork at. The snapshot's LSN will be used.
     */
    snapshot_id?: string | null;
};

/**
 * Request body for merging a source branch into its parent target branch.
 */
export type MergeRequest = {
    /**
     * ID of the target (parent) branch to merge into
     */
    target_branch_id: string;
};

/**
 * Response returned after a successful merge.
 */
export type MergeResponse = {
    /**
     * Updated state of the target branch
     */
    branch: BranchInfo;
    /**
     * Number of object records copied from source onto target
     */
    objects_merged: number;
};

export type ObjectListEntry = {
    content_type: string;
    lsn: number;
    path: string;
    size: number;
};

export type ObjectListResponse = {
    common_prefixes: Array<string>;
    has_more: boolean;
    next_cursor?: string | null;
    objects: Array<ObjectListEntry>;
};

export type PageBranchInfo = {
    has_more: boolean;
    items: Array<{
        branch_id: string;
        created_at: number;
        fork_lsn?: number | null;
        head_lsn: number;
        parent_id?: string | null;
    }>;
    next_cursor?: string | null;
};

export type PageProject = {
    has_more: boolean;
    items: Array<{
        created_at: number;
        default_branch_id: string;
        project_id: string;
    }>;
    next_cursor?: string | null;
};

export type PageSnapshotRecord = {
    has_more: boolean;
    items: Array<{
        branch_id: string;
        created_at: number;
        lsn: number;
        snapshot_id: string;
    }>;
    next_cursor?: string | null;
};

export type Project = {
    created_at: number;
    default_branch_id: string;
    project_id: string;
};

export type ProjectResponse = {
    project: Project;
};

export type PutObjectResponse = {
    created: boolean;
    lsn: number;
    size: number;
};

/**
 * Request body for `restore` (rewind a branch in-place to a specific LSN).
 *
 * Exactly one of `lsn` or `snapshot_id` must be provided.
 * A backup branch is automatically created before the rewind.
 */
export type RestoreRequest = {
    /**
     * LSN to restore to. Must be ≤ the branch's current head LSN.
     */
    lsn?: number | null;
    /**
     * Snapshot ID to restore to. The snapshot's LSN will be used.
     */
    snapshot_id?: string | null;
};

/**
 * Response returned after a successful in-place restore.
 */
export type RestoreResponse = {
    /**
     * Backup branch created to preserve the pre-restore state
     */
    backup_branch: BranchInfo;
    /**
     * The restored branch (same branch_id, rewound to the requested LSN)
     */
    branch: BranchInfo;
};

export type SnapshotRecord = {
    branch_id: string;
    created_at: number;
    lsn: number;
    snapshot_id: string;
};

export type SnapshotResponse = {
    snapshot: SnapshotRecord;
};

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Opaque pagination cursor from a previous response
         */
        cursor?: string;
        /**
         * Maximum number of items to return (1–1000, default 20)
         */
        limit?: number;
    };
    url: '/projects';
};

export type ListProjectsResponses = {
    /**
     * Paginated list of projects
     */
    200: PageProject;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects';
};

export type CreateProjectErrors = {
    /**
     * Project already exists
     */
    409: ErrorEnvelope;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Project created
     */
    201: ProjectResponse;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type DeleteProjectErrors = {
    /**
     * Project not found
     */
    404: ErrorEnvelope;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Project deleted
     */
    204: void;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type GetProjectErrors = {
    /**
     * Project not found
     */
    404: ErrorEnvelope;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
    /**
     * Project found
     */
    200: ProjectResponse;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type ListBranchesData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
    };
    query?: {
        /**
         * Opaque pagination cursor from a previous response
         */
        cursor?: string;
        /**
         * Maximum number of items to return (1–1000, default 20)
         */
        limit?: number;
    };
    url: '/projects/{project_id}/branches';
};

export type ListBranchesErrors = {
    /**
     * Project not found
     */
    404: ErrorEnvelope;
};

export type ListBranchesError = ListBranchesErrors[keyof ListBranchesErrors];

export type ListBranchesResponses = {
    /**
     * Paginated list of branches
     */
    200: PageBranchInfo;
};

export type ListBranchesResponse = ListBranchesResponses[keyof ListBranchesResponses];

export type CreateBranchData = {
    body: CreateBranchRequest;
    path: {
        /**
         * Project ID
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/branches';
};

export type CreateBranchErrors = {
    /**
     * Project or source branch not found
     */
    404: ErrorEnvelope;
};

export type CreateBranchError = CreateBranchErrors[keyof CreateBranchErrors];

export type CreateBranchResponses = {
    /**
     * Branch created
     */
    201: BranchResponse;
};

export type CreateBranchResponse = CreateBranchResponses[keyof CreateBranchResponses];

export type DeleteBranchData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch ID
         */
        branch_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/branches/{branch_id}';
};

export type DeleteBranchErrors = {
    /**
     * Project or branch not found
     */
    404: ErrorEnvelope;
    /**
     * Branch has children or is the default branch
     */
    409: ErrorEnvelope;
};

export type DeleteBranchError = DeleteBranchErrors[keyof DeleteBranchErrors];

export type DeleteBranchResponses = {
    /**
     * Branch deleted
     */
    204: void;
};

export type DeleteBranchResponse = DeleteBranchResponses[keyof DeleteBranchResponses];

export type GetBranchData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch ID
         */
        branch_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/branches/{branch_id}';
};

export type GetBranchErrors = {
    /**
     * Project or branch not found
     */
    404: ErrorEnvelope;
};

export type GetBranchError = GetBranchErrors[keyof GetBranchErrors];

export type GetBranchResponses = {
    /**
     * Branch found
     */
    200: BranchResponse;
};

export type GetBranchResponse = GetBranchResponses[keyof GetBranchResponses];

export type ForkBranchAtLsnData = {
    body: ForkRequest;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch to fork from
         */
        branch_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/branches/{branch_id}/fork';
};

export type ForkBranchAtLsnErrors = {
    /**
     * Invalid LSN or missing/conflicting fork target
     */
    400: ErrorEnvelope;
    /**
     * Project, branch, or snapshot not found
     */
    404: ErrorEnvelope;
};

export type ForkBranchAtLsnError = ForkBranchAtLsnErrors[keyof ForkBranchAtLsnErrors];

export type ForkBranchAtLsnResponses = {
    /**
     * Forked branch created
     */
    201: BranchResponse;
};

export type ForkBranchAtLsnResponse = ForkBranchAtLsnResponses[keyof ForkBranchAtLsnResponses];

export type MergeBranchData = {
    body: MergeRequest;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Source branch ID to merge from
         */
        branch_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/branches/{branch_id}/merge';
};

export type MergeBranchErrors = {
    /**
     * Project or branch not found
     */
    404: ErrorEnvelope;
    /**
     * Source has children or a concurrent merge is in progress
     */
    409: ErrorEnvelope;
    /**
     * Source is not a direct child of target
     */
    422: ErrorEnvelope;
};

export type MergeBranchError = MergeBranchErrors[keyof MergeBranchErrors];

export type MergeBranchResponses = {
    /**
     * Merge successful
     */
    200: MergeResponse;
};

export type MergeBranchResponse = MergeBranchResponses[keyof MergeBranchResponses];

export type ListObjectsData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch ID
         */
        branch_id: string;
    };
    query?: {
        /**
         * Filter to objects whose path starts with this prefix
         */
        prefix?: string;
        /**
         * Group objects by this delimiter (e.g. `/` for virtual directories).
         * Matching common prefixes are returned in `common_prefixes`.
         */
        delimiter?: string;
        /**
         * Opaque pagination cursor from a previous response
         */
        cursor?: string;
        /**
         * Maximum number of objects to return (1–1000, default 100)
         */
        limit?: number;
        /**
         * Return the listing as it existed at this LSN. Omit for the current state.
         */
        at_lsn?: number;
    };
    url: '/projects/{project_id}/branches/{branch_id}/objects';
};

export type ListObjectsErrors = {
    /**
     * Project or branch not found
     */
    404: ErrorEnvelope;
};

export type ListObjectsError = ListObjectsErrors[keyof ListObjectsErrors];

export type ListObjectsResponses = {
    /**
     * Object listing
     */
    200: ObjectListResponse;
};

export type ListObjectsResponse = ListObjectsResponses[keyof ListObjectsResponses];

export type DeleteObjectData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch ID
         */
        branch_id: string;
        /**
         * Object path within the branch
         */
        path: string;
    };
    query?: never;
    url: '/projects/{project_id}/branches/{branch_id}/objects/{path}';
};

export type DeleteObjectErrors = {
    /**
     * Project or branch not found
     */
    404: ErrorEnvelope;
};

export type DeleteObjectError = DeleteObjectErrors[keyof DeleteObjectErrors];

export type DeleteObjectResponses = {
    /**
     * Object deleted
     */
    204: void;
};

export type DeleteObjectResponse = DeleteObjectResponses[keyof DeleteObjectResponses];

export type GetObjectData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch ID
         */
        branch_id: string;
        /**
         * Object path within the branch
         */
        path: string;
    };
    query?: {
        /**
         * Return the object as it existed at this LSN. Omit for the current state.
         */
        at_lsn?: number;
    };
    url: '/projects/{project_id}/branches/{branch_id}/objects/{path}';
};

export type GetObjectErrors = {
    /**
     * Object not found
     */
    404: ErrorEnvelope;
};

export type GetObjectError = GetObjectErrors[keyof GetObjectErrors];

export type GetObjectResponses = {
    /**
     * Object content
     */
    200: Blob | File;
};

export type GetObjectResponse = GetObjectResponses[keyof GetObjectResponses];

export type PutObjectData = {
    /**
     * Raw object content
     */
    body: string;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch ID
         */
        branch_id: string;
        /**
         * Object path within the branch
         */
        path: string;
    };
    query?: never;
    url: '/projects/{project_id}/branches/{branch_id}/objects/{path}';
};

export type PutObjectErrors = {
    /**
     * Project or branch not found
     */
    404: ErrorEnvelope;
};

export type PutObjectError = PutObjectErrors[keyof PutObjectErrors];

export type PutObjectResponses = {
    /**
     * Object overwritten
     */
    200: PutObjectResponse;
    /**
     * Object created
     */
    201: PutObjectResponse;
};

export type PutObjectResponse2 = PutObjectResponses[keyof PutObjectResponses];

export type ResetBranchFromParentData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch to reset
         */
        branch_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/branches/{branch_id}/reset';
};

export type ResetBranchFromParentErrors = {
    /**
     * Project or branch not found
     */
    404: ErrorEnvelope;
    /**
     * Branch has no parent (is the root branch)
     */
    422: ErrorEnvelope;
};

export type ResetBranchFromParentError = ResetBranchFromParentErrors[keyof ResetBranchFromParentErrors];

export type ResetBranchFromParentResponses = {
    /**
     * Branch reset
     */
    200: BranchResponse;
};

export type ResetBranchFromParentResponse = ResetBranchFromParentResponses[keyof ResetBranchFromParentResponses];

export type RestoreBranchData = {
    body: RestoreRequest;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch to restore
         */
        branch_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/branches/{branch_id}/restore';
};

export type RestoreBranchErrors = {
    /**
     * Invalid LSN or missing/conflicting restore target
     */
    400: ErrorEnvelope;
    /**
     * Project, branch, or snapshot not found
     */
    404: ErrorEnvelope;
};

export type RestoreBranchError = RestoreBranchErrors[keyof RestoreBranchErrors];

export type RestoreBranchResponses = {
    /**
     * Branch restored; backup branch created
     */
    200: RestoreResponse;
};

export type RestoreBranchResponse = RestoreBranchResponses[keyof RestoreBranchResponses];

export type ListSnapshotsData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch ID
         */
        branch_id: string;
    };
    query?: {
        /**
         * Opaque pagination cursor from a previous response
         */
        cursor?: string;
        /**
         * Maximum number of items to return (1–1000, default 20)
         */
        limit?: number;
    };
    url: '/projects/{project_id}/branches/{branch_id}/snapshots';
};

export type ListSnapshotsErrors = {
    /**
     * Project or branch not found
     */
    404: ErrorEnvelope;
};

export type ListSnapshotsError = ListSnapshotsErrors[keyof ListSnapshotsErrors];

export type ListSnapshotsResponses = {
    /**
     * Paginated list of snapshots
     */
    200: PageSnapshotRecord;
};

export type ListSnapshotsResponse = ListSnapshotsResponses[keyof ListSnapshotsResponses];

export type CreateSnapshotData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch ID
         */
        branch_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/branches/{branch_id}/snapshots';
};

export type CreateSnapshotErrors = {
    /**
     * Project or branch not found
     */
    404: ErrorEnvelope;
};

export type CreateSnapshotError = CreateSnapshotErrors[keyof CreateSnapshotErrors];

export type CreateSnapshotResponses = {
    /**
     * Snapshot created
     */
    201: SnapshotResponse;
};

export type CreateSnapshotResponse = CreateSnapshotResponses[keyof CreateSnapshotResponses];

export type DeleteSnapshotData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch ID
         */
        branch_id: string;
        /**
         * Snapshot ID
         */
        snapshot_name: string;
    };
    query?: never;
    url: '/projects/{project_id}/branches/{branch_id}/snapshots/{snapshot_name}';
};

export type DeleteSnapshotErrors = {
    /**
     * Project, branch, or snapshot not found
     */
    404: ErrorEnvelope;
};

export type DeleteSnapshotError = DeleteSnapshotErrors[keyof DeleteSnapshotErrors];

export type DeleteSnapshotResponses = {
    /**
     * Snapshot deleted
     */
    204: void;
};

export type DeleteSnapshotResponse = DeleteSnapshotResponses[keyof DeleteSnapshotResponses];

export type GetSnapshotData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project_id: string;
        /**
         * Branch ID
         */
        branch_id: string;
        /**
         * Snapshot ID
         */
        snapshot_name: string;
    };
    query?: never;
    url: '/projects/{project_id}/branches/{branch_id}/snapshots/{snapshot_name}';
};

export type GetSnapshotErrors = {
    /**
     * Project, branch, or snapshot not found
     */
    404: ErrorEnvelope;
};

export type GetSnapshotError = GetSnapshotErrors[keyof GetSnapshotErrors];

export type GetSnapshotResponses = {
    /**
     * Snapshot found
     */
    200: SnapshotResponse;
};

export type GetSnapshotResponse = GetSnapshotResponses[keyof GetSnapshotResponses];
